ENV:
  gpus: "'2'"
EXECUTION:
  name: GExecution
  resume: False 
  loaded_checkpoint_path: None 
  log_path: train_info_{version}.txt
  version: GATLangGraph
  save_path: checkpoints_{version}/
  output_steps: 10
  ren_mode: train

OPTIM:
  lr_base: 0.0001
  lr_scheduler: warmup
  grad_accu_step: 1
  opt_betas: (0.9, 0.98)
  opt_eps: 1e-9
  step: 2
  step2: 20

MODEL:
  name: GATLangGraph
  vocab_size: 12941
  embeded_size: 300
  parent_path: /cw/liir/NoCsBack/testliir/datasets/
  pretrained_word_path: KR_VQR/glove.42B.300d/glove.42B.300d.txt
  word2index_path: KR_VQR/word2index.json
  num_layers: 3
  max_img_node_len: 10
  max_img_edge_len: 10
  max_kg_len: 10
  max_lang_edges: 40
  use_glove_emb: True
  fine_tune: False
  hidden_size: 512
  num_answer: 6900
  LANG_GRAPH:
    in_dim: 512
    out_dim: 512
    num_heads: 4
  GCN:
    in_dim: 512
    rel_dim: 512 
    out_dim: 512 
  CROSS_ATT:
    in_dim: 512
    hidden_size: 512
    att_node_size: 512
    att_edge_size: 512
    node_size: 512
    edge_size: 512
  PRED_HEAD:
    num_answers: 6900
    hidden_size: 512
  LANG_ENCODER:
    rnn_type: lstm
    input_size: 300
    hidden_size: 512
    num_layers: 2
    bidirectional: False
    dropout: 0.1
    output_last_layer: True

DATA:
  name: GraphDataset
  candidate_answer_path: KR_VQR/candidate_answers.json
  img_feature_path: /export/home2/NoCsBack/hci/mingxiao/feats/vg_objects.lmdb
  max_region: 36
  max_num_img_node: 80
  max_img_node_len: 10
  max_num_img_edge: 100
  max_img_edge_len: 10
  max_seq_len: 32
  k_nearest: 5
  split: train 
  path: KR_VQR/clean_{split}.json
  ori_region_loc: True
  load_retrieval_kg: True 
  num_kg_entity: 10
  max_kg_ele_len: 10
  use_scene_graph: True 
  word_count_path: KR_VQR/reason_data_triplet_word_count.json
  use_symbolic: False
  kg_path: KR_VQR/all_fact_list.json
  retrieval_kg_path: KR_VQR/retrieval_out.json
  top_k_kg: 10
  kg_to_lang_path: KR_VQR/knowledge_triplet_language.json
  word2index_path: KR_VQR/word2index.json
  scene_graph_path: KR_VQR/vg_scene_graph.json
  valid_batch_size: 128
  max_num_lang_graph_edge: 40 
  use_lang_graph: True
  load_connection_from_file: True 
  connection_path: KR_VQR/clean_{split}_lang_connections.json
