ENV:
  gpus: "'3'"

EXECUTION:
  name:
  resume: False
  loaded_checkpoint_path: None
  log_path: train_info_{version}.txt
  version: rf_with_gt
  save_path: checkpoints_{version}/
  output_steps: 10
  run_mode: train

MODEL:
  name: RFNet
  Language:
    vocab_size:
    embeded_size: 300
    input_size:
    hidden_size:
    num_layers:
    dropout:
    rnn_type: lstm
    bidirectional:
  hidden_size:
  img_size: 2048
  loc_size:
  query_node_size:
  key_node_size:
  mlp_mid_size:
  query_edge_size:
  key_edge_size:
  query_size:
  node_size:
  num_class: 6900

OPTIM:
  lr_base: 0.0001
  lr_scheduler: warmup
  grad_accu_steps: 1
  opt_betas: (0.9, 0.98)
  opt_eps: 1e-9
  step: 2
  step2: 20

DATA:
  name: RFDataset
  split: train
  path: KR_VQR/{split}_krvqr.json
  rel_to_lang_path: KR_VQR/knowledge_triplet_language.json
  word_count_path: KR_VQR/reason_data_triplet_word_count.json
  candidate_answer_path: KR_VQR/candidate_answers.json
  image_feature_path: /export/home2/NoCsBack/hci/mingxiao/feats/vg_objects.lmdb
  kg_to_lang_path: KR_VQR/knowledge_triplet_language.json
  batch_size: 1
  max_seq_len: 32
  max_entity_len: 10
  max_num_kg: 1
  shuffle: True
  valid_batch_size: 1
  k_nearest_node: 5
  only_kb_not_related: False
  only_kb_related: True
  only_q_type: None
  RF_SETUP:
    setup: gt
  KG_SETUP:
    setup: gt