DATA:
  name: GraphDataset
  candidate_answer_path: KR_VQR/candidate_answers.json
  img_feature_path: /export/home2/NoCsBack/hci/mingxiao/feats/vg_object_cls.lmdb
  max_region: 36
  max_num_img_node: 40
  max_img_node_len: 10
  max_num_img_edge: 100
  max_img_edge_len: 10
  max_seq_len: 32
  k_nearest: 5
  split: train
  path: KR_VQR/clean_{split}.json
  ori_region_loc: True
  load_retrieval_kg: True 
  num_kg_entity: 10
  max_kg_ele_len: 10
  use_scene_graph: True 
  word_count_path: KR_VQR/reason_data_triplet_word_count.json
  use_symbolic: True
  kg_path: KR_VQR/all_fact_list.json
  retrieval_kg_path: KR_VQR/retrieval_out.json
  top_k_kg: 10
  kg_to_lang_path: KR_VQR/knowledge_triplet_language.json
  word2index_path: KR_VQR/word2index.json
  scene_graph_path: KR_VQR/vg_scene_graph.json
  valid_batch_size: 128
  max_num_lang_graph_edge: 40 
  use_lang_graph: False
  load_connection_from_file: True 
  connection_path: KR_VQR/clean_{split}_lang_connections.json
  object_path: KR_VQR/rcnn_objects.json
  put_answer_in_graph: False
  synset_path: KR_VQR/synsets.json
  use_gt_sg: False
  ge_scene_graph_info: visual_genome/GeneratedSceneGraph/vg_pred_info.json  
  ge_scene_graph: visual_genome/GeneratedSceneGraph/vg_pred_sg.h5